# ========== TROPHIES ==========
trophies:
  player_kill: 10
# ========== STORAGE ==========
storage:
  type: mysql
  settings:
    host: "localhost"
    port: 3306
    database: "minecraft"
    username: "root"
    password: ""
    ssl: false
# ========== CASTLE ===========
castle:
  world: "nefario"
# ========== MESSAGE ==========
messages:
  full_inventory: "<bold><red>IL TUO INVENTARIO È PIENO</red></bold>"
  not_in_clan: "<bold><red>NON SEI IN NESSUN CLAN</red></bold>"
  not_leader: "<bold><red>NON SEI IL LEADER DEL CLAN</red></bold>"
  guardian_spawner:
    block_name: "FAI NASCERE IL TUO GUARDIANO"
    description:
      - "Prima riga del blocco"
      - "Seconda riga"











# NON TOCCARE
config_version: 3